### ISSUE TITLE
How to add “jquery.flowchart” to my Angular program?

### ISSUE THREAD

**Issue by hooshbartar** [nephilimboy/Angular_FlowChartJS#2]
Hi,
Thanks for GREAT project!

I made a new Angular project, created a new component named `flow` and tried to copy the content of `app.component.html` and `app.component.ts` and `flowchartJs.css` files to my program's `flow.component.html` and `flow.component.ts` and `flow.component.scss` files. I also looked at the `pakage.json` file and added some dependencies that my new app hadn't have compare to `Angular_FlowChartJS` app. Also added `JS` folder into my app.

I compiled(`npm install`) and ran my program(`npm start`) and it looks fine but the flowchart buttons seems doesn't work. So I can't add new operator to the screen and work on them.

As I am a new Angular developer please help me to understand what is the problem and what more modifications should I do?

**Comment by nephilimboy** [comment]
Hi,, 
Sorry for the late reply
I recommend that you first run the original project (that ive committed here) and see if you have the same problem or not. if the project run correctly and the buttons work fine then the problem comes from your source code. After that plz post your project build log here. also it would be helpful if you post the browser's console log during the "button click" here as well.

**Comment by hooshbartar** [comment]
> Hi,,
> Sorry for the late reply
> I recommend that you first run the original project (that ive committed here) and see if you have the same problem or not. if the project run correctly and the buttons work fine then the problem comes from your source code. After that plz post your project build log here. also it would be helpful if you post the browser's console log during the "button click" here as well.

Hello @nephilimboy ,
I am also so sorry for my late answer because of our Internet problem in our country! BTW I commited my full project here: https://github.com/hooshbartar/test

I put your code in `flow` component and in the demo website you can find it in "ساخت استراتژی" tab from web site header.

**Comment by hooshbartar** [comment]
This is the error I do get:
```

FlowComponent.html:3 ERROR ReferenceError: $ is not defined
    at FlowComponent.addNewOperator (flow.component.ts:147)
    at Object.eval [as handleEvent] (FlowComponent.html:9)
    at handleEvent (core.js:38098)
    at callWithDebugContext (core.js:39716)
    at Object.debugHandleEvent [as handleEvent] (core.js:39352)
    at dispatchEvent (core.js:25818)
    at core.js:37030
    at HTMLInputElement.<anonymous> (platform-browser.js:1789)
    at ZoneDelegate.invokeTask (zone-evergreen.js:391)
    at Object.onInvokeTask (core.js:34182)
View_FlowComponent_0 @ FlowComponent.html:3
proxyClass @ compiler.js:19436
logError @ core.js:39651
handleError @ core.js:9162
dispatchEvent @ core.js:25822
(anonymous) @ core.js:37030
(anonymous) @ platform-browser.js:1789
invokeTask @ zone-evergreen.js:391
onInvokeTask @ core.js:34182
invokeTask @ zone-evergreen.js:390
runTask @ zone-evergreen.js:168
invokeTask @ zone-evergreen.js:465
invokeTask @ zone-evergreen.js:1603
globalZoneAwareCallback @ zone-evergreen.js:1629
FlowComponent.html:3 ERROR CONTEXT DebugContext_ {view: {…}, nodeIndex: 3, nodeDef: {…}, elDef: {…}, elView: {…}}
```

**Comment by nephilimboy** [comment]
Hi,
There are some solutions for this issue, you may use either "**angular-cli.json**" file or "**package.json**" (i used this one) to solve this problem. check the link below for more info https://stackoverflow.com/questions/41801754/jquery-is-not-defined-for-angular-2
Feel free to ask extra questions!

**Comment by hooshbartar** [comment]
> Hi,
> There are some solutions for this issue, you may use either "**angular-cli.json**" file or "**package.json**" (i used this one) to solve this problem. check the link below for more info https://stackoverflow.com/questions/41801754/jquery-is-not-defined-for-angular-2
> Feel free to ask extra questions!

Thank you @nephilimboy , But as I use Angular 8 I think I don't have `angular-cli` file in my project. I also tried to add this line `"node_modules/jquery/dist/jquery.min.js"` to the script array inside my `angular.json` file but didn't work because I get this new error:
```

FlowComponent_Host.ngfactory.js? [sm]:1 ERROR TypeError: $(...).panzoom is not a function
    at FlowComponent.ngAfterViewInit (flow.component.ts:58)
    at callProviderLifecycles (core.js:28206)
    at callElementProvidersLifecycles (core.js:28171)
    at callLifecycleHooksChildrenFirst (core.js:28153)
    at checkAndUpdateView (core.js:38386)
    at callViewAction (core.js:38742)
    at execEmbeddedViewsAction (core.js:38699)
    at checkAndUpdateView (core.js:38377)
    at callViewAction (core.js:38742)
    at execComponentViewsAction (core.js:38670)
View_FlowComponent_Host_0 @ FlowComponent_Host.ngfactory.js? [sm]:1
proxyClass @ compiler.js:19436
logError @ core.js:39651
handleError @ core.js:9162
(anonymous) @ core.js:35393
invoke @ zone-evergreen.js:359
run @ zone-evergreen.js:124
runOutsideAngular @ core.js:34127
tick @ core.js:35390
(anonymous) @ core.js:35228
invoke @ zone-evergreen.js:359
onInvoke @ core.js:34201
invoke @ zone-evergreen.js:358
run @ zone-evergreen.js:124
run @ core.js:34066
next @ core.js:35225
schedulerFn @ core.js:31051
__tryOrUnsub @ Subscriber.js:185
next @ Subscriber.js:124
_next @ Subscriber.js:72
next @ Subscriber.js:49
next @ Subject.js:39
emit @ core.js:31013
checkStable @ core.js:34144
onHasTask @ core.js:34221
hasTask @ zone-evergreen.js:411
_updateTaskCount @ zone-evergreen.js:431
_updateTaskCount @ zone-evergreen.js:264
runTask @ zone-evergreen.js:185
drainMicroTaskQueue @ zone-evergreen.js:559
Promise.then (async)
scheduleMicroTask @ zone-evergreen.js:542
scheduleTask @ zone-evergreen.js:381
scheduleTask @ zone-evergreen.js:211
scheduleMicroTask @ zone-evergreen.js:231
scheduleResolveOrReject @ zone-evergreen.js:845
then @ zone-evergreen.js:955
bootstrapModule @ core.js:34957
./src/main.ts @ main.ts:11
__webpack_require__ @ bootstrap:79
0 @ main.ts:12
__webpack_require__ @ bootstrap:79
checkDeferredModules @ bootstrap:45
webpackJsonpCallback @ bootstrap:32
(anonymous) @ main.js:1
FlowComponent_Host.ngfactory.js? [sm]:1 ERROR CONTEXT DebugContext_ {view: {…}, nodeIndex: 1, nodeDef: {…}, elDef: {…}, elView: {…}}
```

**Comment by hooshbartar** [comment]
I could solve the above problem by adding this new line `"node_modules/jquery.panzoom/dist/jquery.panzoom.min.js" ` to the `angular.js` file too but new error:

ERROR TypeError: $(...).flowchart is not a function
    at FlowComponent.addNewOperator (flow.component.ts:147)
    at Object.eval [as handleEvent] (FlowComponent.html:9)
    at handleEvent (core.js:38098)
    at callWithDebugContext (core.js:39716)
    at Object.debugHandleEvent [as handleEvent] (core.js:39352)
    at dispatchEvent (core.js:25818)
    at core.js:37030
    at HTMLInputElement.<anonymous> (platform-browser.js:1789)
    at ZoneDelegate.invokeTask (zone-evergreen.js:391)
    at Object.onInvokeTask (core.js:34182)
View_FlowComponent_0 @ FlowComponent.html:3
proxyClass @ compiler.js:19436
logError @ core.js:39651
handleError @ core.js:9162
dispatchEvent @ core.js:25822
(anonymous) @ core.js:37030
(anonymous) @ platform-browser.js:1789
invokeTask @ zone-evergreen.js:391
onInvokeTask @ core.js:34182
invokeTask @ zone-evergreen.js:390
runTask @ zone-evergreen.js:168
invokeTask @ zone-evergreen.js:465
invokeTask @ zone-evergreen.js:1603
globalZoneAwareCallback @ zone-evergreen.js:1629
FlowComponent.html:3 ERROR CONTEXT DebugContext_ {view: {…}, nodeIndex: 3, nodeDef: {…}, elDef: {…}, elView: {…}}

**Comment by hooshbartar** [comment]
@nephilimboy , I could solve the above problems and now it works fine with no errors but the only problem is this:

![ops](https://user-images.githubusercontent.com/57624409/69647387-a1851a80-107e-11ea-9ade-1f985706cb1e.png)


I don't know why it doesn't show correctly?

**Comment by hooshbartar** [comment]
I also like to know if I want to add a palette to this project that I can put some pre-built operator blocks there, then user can drag and drop them into the screen(instead of pushing buttons like your project) how can I do it? I mean what plugins or modules or even open source projects/codes are there to use or see and learn?

**Comment by hooshbartar** [comment]
Finally I could solve my problem by putting `css` file into the root directory of the project like your demo project. Before that I copied it into `scss` file of my compont and it was not working properly.
